apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: study-note
resources:
  - ../../base
images:
  - name: 000000000000.dkr.ecr.ap-northeast-2.amazonaws.com/study-note-backend
    newName: 107015853205.dkr.ecr.ap-northeast-2.amazonaws.com/study-note-backend
    newTag: ff73fe82592e1a6f7e32daebfec2efbee21bc15f
  - name: 000000000000.dkr.ecr.ap-northeast-2.amazonaws.com/study-note-frontend
    newName: 107015853205.dkr.ecr.ap-northeast-2.amazonaws.com/study-note-frontend
    newTag: ff73fe82592e1a6f7e32daebfec2efbee21bc15f
