apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - ingress-ip-fallback.yaml
  - ingress-www.yaml
  - middleware-https-redirect.yaml
  - middleware-www-redirect.yaml
  - ecr-refresh-rbac.yaml
  - ecr-refresh-cronjob.yaml
